### ISSUE TITLE
Feature Selection dengan menggunakan RandomForest

### ISSUE THREAD

**Issue by rudyhendrawn** [YOGASATWIKA/datamining#11]

**Comment by rudyhendrawn** [comment]
Dataset tidak perlu dibagi ketika melakukan feature selection.

**Feature Selection using Random Forest**
`X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)` in [EDA-feature-selection](https://github.com/YOGASATWIKA/datamining/blob/main/eda-feature-selection.ipynb).

@premaagung @QueenChangge @YOGASATWIKA

**Comment by premaagung** [comment]
Siap pak

**Comment by premaagung** [comment]
> Dataset tidak perlu dibagi ketika melakukan feature selection.
> 
> **Feature Selection using Random Forest** `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)` in [EDA-feature-selection](https://github.com/YOGASATWIKA/datamining/blob/main/eda-feature-selection.ipynb).
> 
> @premaagung @QueenChangge @YOGASATWIKA

Siap pak
